In [9]:
import pandas as pd

T6_KEPLER = pd.read_csv('kepler_Neuronet_20250805_090528.csv')
T6_KEPLER['_time'] = pd.to_datetime(T6_KEPLER['_time'])
T5_K8S = pd.read_csv('k8s_Neuronet_20250805_090507.csv')
T5_K8S['_time'] = pd.to_datetime(T5_K8S['_time'])
T4_SCA_VM = pd.read_csv('scaphandre_neuronet_20250805_090241.csv')
T4_SCA_VM['_time'] = pd.to_datetime(T4_SCA_VM['_time'])
T3_SCA_HT_3 = pd.read_csv('scaphandre_flux-node3_20250805_090248.csv')
T3_SCA_HT_4 = pd.read_csv('scaphandre_flux-node4_20250805_090248.csv')
T3_SCA_HT_5 = pd.read_csv('scaphandre_flux-node5_20250805_090249.csv')
T3_SCA_HT = pd.concat([T3_SCA_HT_3, T3_SCA_HT_4, T3_SCA_HT_5])
T3_SCA_HT['_time'] = pd.to_datetime(T3_SCA_HT['_time'])
T2_PDU_1 = pd.read_csv('pdu_flux-node1_20250805_090211.csv')
T2_PDU_3 = pd.read_csv('pdu_flux-node3_20250805_090214.csv')
T2_PDU_4 = pd.read_csv('pdu_flux-node4_20250805_090217.csv')
T2_PDU_5 = pd.read_csv('pdu_flux-node5_20250805_090219.csv')
T2_PDU = pd.concat([T2_PDU_1, T2_PDU_3, T2_PDU_4, T2_PDU_5])
T2_PDU['_time'] = pd.to_datetime(T2_PDU['_time'])
T1_PROXMOX = pd.read_csv('proxmox_neuronet_20250805_090202.csv')
T1_PROXMOX['_time'] = pd.to_datetime(T1_PROXMOX['_time'])

/tmp/ipykernel_198714/3797652977.py:5: DtypeWarning: Columns (8,12,15) have mixed types. Specify dtype option on import or set low_memory=False.
  T5_K8S = pd.read_csv('k8s_Neuronet_20250805_090507.csv')

In [2]:
# Merge T6_KEPLER with T5_K8S on time and pod_name
df_step1 = pd.merge_asof(T6_KEPLER.sort_values('_time'), T5_K8S.sort_values('_time'), on='_time', by='pod_name', direction='nearest')
print(df_step1.shape)
df_step1.head()

(12496, 31)

,result_x,table_x,_start_x,_stop_x,_time,_value_x,_field_x,_measurement_x,container_id,container_name_x,...,_value_y,_field_y,_measurement_y,container_name_y,inventory-cluster-id_y,inventory-rack-id_y,inventory-server-id_y,namespace_y,node_name,plugin_y
0,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,8839.443,kepler_container_joules_total,energy_measurements,14bc8c204d73135d6e65e27faaad06614517929ed9b27f...,kube-scheduler,...,2.365121e+11,cpu_usage_core_nanoseconds,computational_measurements,kube-scheduler,flux,r4,Neuronet-Cluster,kube-system,neuronet-m1,k8s
1,_result,3,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,1601231756754091e5b1012a3179398d3f9885565dc457...,ovs-cni-plugin,...,4.000612e+09,available_bytes,computational_measurements,NaN,flux,r4,Neuronet-Cluster,cluster-network-addons,neuronet-m1,k8s
2,_result,28,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_joules_total,energy_measurements,a236b375f5058ee31c0a2964972fb9c64a7a7af6ee9850...,install-multus-binary,...,4.232897e+11,tx_bytes,computational_measurements,NaN,flux,r4,Neuronet-Cluster,kube-system,neuronet-m1,k8s
3,_result,29,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,a236b375f5058ee31c0a2964972fb9c64a7a7af6ee9850...,install-multus-binary,...,4.232897e+11,tx_bytes,computational_measurements,NaN,flux,r4,Neuronet-Cluster,kube-system,neuronet-m1,k8s
4,_result,30,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,1932217.350,kepler_container_joules_total,energy_measurements,a54dd4d5f3802c39910f5785896517f9818524dd5c911d...,kepler-exporter,...,1.691876e+13,cpu_usage_core_nanoseconds,computational_measurements,kepler-exporter,flux,r4,Neuronet-Cluster,optimiter,neuronet-m1,k8s

In [3]:
# Merge df with T4_SCA_VM on time and node_name (in T4_SCA_VM node_name is named vm_name)
df_step2 = pd.merge_asof(df_step1.sort_values('_time'), T4_SCA_VM.sort_values('_time'), left_on='_time', right_on='_time', left_by='node_name', right_by='vm_name', direction='nearest')
print(df_step2.shape)
df_step2.head()

(12496, 49)

,result_x,table_x,_start_x,_stop_x,_time,_value_x,_field_x,_measurement_x,container_id,container_name_x,...,exe,granularity,inventory-cluster-id,inventory-rack-id,plugin,system_type,url_y,uuid,vm_id,vm_name
0,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,8.839443e+03,kepler_container_joules_total,energy_measurements,14bc8c204d73135d6e65e27faaad06614517929ed9b27f...,kube-scheduler,...,/usr/bin/qemu-system-x86_64,host+process,flux,r4,scaphandre,kvm,http://flux-node4.av.it.pt:8080/metrics,c5237c73-cef8-42c1-bc97-fe0982b9d219,179.0,neuronet-m1
1,_result,11,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,3.056730e+07,kepler_container_microwatts_consumption_total,energy_measurements,460fb9776671b6715c9b3d5ee5eaded3c71b4940b85eba...,kube-apiserver,...,/usr/bin/qemu-system-x86_64,host+process,flux,r4,scaphandre,kvm,http://flux-node4.av.it.pt:8080/metrics,c5237c73-cef8-42c1-bc97-fe0982b9d219,179.0,neuronet-m1
2,_result,12,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,5.818690e+05,kepler_container_joules_total,energy_measurements,52062c3ac390efee82962bbbfe0a794f98c46cba55d1c7...,node-exporter,...,/usr/bin/qemu-system-x86_64,host+process,flux,r4,scaphandre,kvm,http://flux-node4.av.it.pt:8080/metrics,c5237c73-cef8-42c1-bc97-fe0982b9d219,179.0,neuronet-m1
3,_result,13,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,3.010500e+05,kepler_container_microwatts_consumption_total,energy_measurements,52062c3ac390efee82962bbbfe0a794f98c46cba55d1c7...,node-exporter,...,/usr/bin/qemu-system-x86_64,host+process,flux,r4,scaphandre,kvm,http://flux-node4.av.it.pt:8080/metrics,c5237c73-cef8-42c1-bc97-fe0982b9d219,179.0,neuronet-m1
4,_result,14,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000000e+00,kepler_container_joules_total,energy_measurements,54214052d6488368b43da0b892d078b29cb5aa8432d1b4...,install-cni-plugin,...,/usr/bin/qemu-system-x86_64,host+process,flux,r4,scaphandre,kvm,http://flux-node4.av.it.pt:8080/metrics,c5237c73-cef8-42c1-bc97-fe0982b9d219,179.0,neuronet-m1

In [14]:
# merge df with T3_SCA_HT on time and url on both sides
df_step3 = pd.merge_asof(df_step2.sort_values('_time'), T3_SCA_HT.sort_values('_time'), left_on='_time', right_on='_time', left_by='url_y', right_by='url', direction='nearest', suffixes=('_step2', '_sca'))
print(df_step3.shape)
df_step3.head()

(12496, 61)

,result_x,table_x,_start_x,_stop_x,_time,_value_x,_field_x,_measurement_x,container_id,container_name_x,...,_start_sca,_stop_sca,_value_sca,_field_sca,_measurement_sca,granularity_sca,inventory-cluster-id_sca,inventory-rack-id_sca,plugin_sca,url
0,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,8839.443,kepler_container_joules_total,energy_measurements,14bc8c204d73135d6e65e27faaad06614517929ed9b27f...,kube-scheduler,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics
1,_result,25,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,788650fc8eae0ee1a0c0ceb7cfe660fea00cc219e1b669...,kube-multus,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics
2,_result,3,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,1601231756754091e5b1012a3179398d3f9885565dc457...,ovs-cni-plugin,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics
3,_result,28,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_joules_total,energy_measurements,a236b375f5058ee31c0a2964972fb9c64a7a7af6ee9850...,install-multus-binary,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics
4,_result,29,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,a236b375f5058ee31c0a2964972fb9c64a7a7af6ee9850...,install-multus-binary,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics

In [17]:
df_step3['node'] = df_step3['url'].str.extract(r'http://(flux-node\d+)')
df_step3.head()

,result_x,table_x,_start_x,_stop_x,_time,_value_x,_field_x,_measurement_x,container_id,container_name_x,...,_stop_sca,_value_sca,_field_sca,_measurement_sca,granularity_sca,inventory-cluster-id_sca,inventory-rack-id_sca,plugin_sca,url,node
0,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,8839.443,kepler_container_joules_total,energy_measurements,14bc8c204d73135d6e65e27faaad06614517929ed9b27f...,kube-scheduler,...,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics,flux-node4
1,_result,25,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,788650fc8eae0ee1a0c0ceb7cfe660fea00cc219e1b669...,kube-multus,...,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics,flux-node4
2,_result,3,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,1601231756754091e5b1012a3179398d3f9885565dc457...,ovs-cni-plugin,...,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics,flux-node4
3,_result,28,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_joules_total,energy_measurements,a236b375f5058ee31c0a2964972fb9c64a7a7af6ee9850...,install-multus-binary,...,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics,flux-node4
4,_result,29,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,a236b375f5058ee31c0a2964972fb9c64a7a7af6ee9850...,install-multus-binary,...,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics,flux-node4

In [19]:
# merge df with T2_PDU on time and inventory server id and node in df_step3
df_step4 = pd.merge_asof(df_step3.sort_values('_time'), T2_PDU.sort_values('_time'), left_on='_time', right_on='_time', left_by='node', right_by='inventory-server-id', direction='nearest', suffixes=('_step3', '_pdu'))
print(df_step4.shape)
df_step4.head()

(12496, 74)

,result_x,table_x,_start_x,_stop_x,_time,_value_x,_field_x,_measurement_x,container_id,container_name_x,...,_start,_stop,_value,_field,_measurement,inventory-rack-id,inventory-server-id,placement,plugin,url_pdu
0,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,8.839443e+03,kepler_container_joules_total,energy_measurements,14bc8c204d73135d6e65e27faaad06614517929ed9b27f...,kube-scheduler,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,1.763,peakFactor,energy_measurements,r4,flux-node4,left,pdu,https://192.168.88.145/rest/mbdetnrs/2.0/power...
1,_result,23,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,9.415950e+06,kepler_container_microwatts_consumption_total,energy_measurements,77f43f3bb89ebcd89a09cf5227e295c3aa5d4457c4cfff...,kube-controller-manager,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,1.763,peakFactor,energy_measurements,r4,flux-node4,left,pdu,https://192.168.88.145/rest/mbdetnrs/2.0/power...
2,_result,11,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,3.056730e+07,kepler_container_microwatts_consumption_total,energy_measurements,460fb9776671b6715c9b3d5ee5eaded3c71b4940b85eba...,kube-apiserver,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,1.763,peakFactor,energy_measurements,r4,flux-node4,left,pdu,https://192.168.88.145/rest/mbdetnrs/2.0/power...
3,_result,12,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,5.818690e+05,kepler_container_joules_total,energy_measurements,52062c3ac390efee82962bbbfe0a794f98c46cba55d1c7...,node-exporter,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,1.763,peakFactor,energy_measurements,r4,flux-node4,left,pdu,https://192.168.88.145/rest/mbdetnrs/2.0/power...
4,_result,13,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,3.010500e+05,kepler_container_microwatts_consumption_total,energy_measurements,52062c3ac390efee82962bbbfe0a794f98c46cba55d1c7...,node-exporter,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,1.763,peakFactor,energy_measurements,r4,flux-node4,left,pdu,https://192.168.88.145/rest/mbdetnrs/2.0/power...

In [16]:
T2_PDU.head()

,result,table,_start,_stop,_time,_value,_field,_measurement,inventory-rack-id,inventory-server-id,placement,plugin,url
0,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:31+00:00,67.001,activePower,energy_measurements,r4,flux-node1,left,pdu,https://192.168.88.145/rest/mbdetnrs/2.0/power...
1,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:01:03+00:00,71.235,activePower,energy_measurements,r4,flux-node1,left,pdu,https://192.168.88.145/rest/mbdetnrs/2.0/power...
2,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:01:32+00:00,66.615,activePower,energy_measurements,r4,flux-node1,left,pdu,https://192.168.88.145/rest/mbdetnrs/2.0/power...
3,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:02:03+00:00,66.361,activePower,energy_measurements,r4,flux-node1,left,pdu,https://192.168.88.145/rest/mbdetnrs/2.0/power...
4,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:02:33+00:00,66.659,activePower,energy_measurements,r4,flux-node1,left,pdu,https://192.168.88.145/rest/mbdetnrs/2.0/power...

In [15]:
df_step3.head()

,result_x,table_x,_start_x,_stop_x,_time,_value_x,_field_x,_measurement_x,container_id,container_name_x,...,_start_sca,_stop_sca,_value_sca,_field_sca,_measurement_sca,granularity_sca,inventory-cluster-id_sca,inventory-rack-id_sca,plugin_sca,url
0,_result,0,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,8839.443,kepler_container_joules_total,energy_measurements,14bc8c204d73135d6e65e27faaad06614517929ed9b27f...,kube-scheduler,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics
1,_result,25,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,788650fc8eae0ee1a0c0ceb7cfe660fea00cc219e1b669...,kube-multus,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics
2,_result,3,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,1601231756754091e5b1012a3179398d3f9885565dc457...,ovs-cni-plugin,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics
3,_result,28,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_joules_total,energy_measurements,a236b375f5058ee31c0a2964972fb9c64a7a7af6ee9850...,install-multus-binary,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics
4,_result,29,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,2025-08-04 06:00:00+00:00,0.000,kepler_container_microwatts_consumption_total,energy_measurements,a236b375f5058ee31c0a2964972fb9c64a7a7af6ee9850...,install-multus-binary,...,2025-08-04 06:00:00+00:00,2025-08-04 11:00:00+00:00,63426249.0,scaph_host_power_microwatts,energy_measurements,host+process,flux,r4,scaphandre,http://flux-node4.av.it.pt:8080/metrics